### ISSUE TITLE
Breakout action space decreased

### ISSUE THREAD

**Issue by Breakend** [openai/atari-py#16]
Hi,

I'm a bit curious as to why the Breakout action space was decreased from 6 to 4. I'm doing some research in transfer/multitask learning and this was a breaking change for me. While maybe this is the desired choice down the line, I'd like to suggest restoring it such that several environments with similar goals (breakout/pong) have the same action spaces. In any case, I'm opening this issue to see if there was some reasoning behind it.

Thanks.

**Comment by wookayin** [comment]
See commit 199fdf3ac3e

**Comment by christopherhesse** [comment]
Thanks for answering this @wookayin!  I think that you might want to use the full action space rather than the minimal one, as that should rarely change and probably makes more sense for transfer/multitask anyway, does that sound reasonable @Breakend?
