### ISSUE TITLE
Unable to Use; Basic Steps?

### ISSUE THREAD

**Issue by jeffnyman** [openai/atari-py#17]
I fear I'm being very foolish here but my understanding is that this is a packaging up of ale_python_interface. So I have done the install (on Mac):

    pip install atari-py

Then, from a Python prompt, I tried:

    from ale_python_interface import ALEInterface

That does not work. (No module named "ale_python_interface".) So then I cloned the repo and tried the build:

    python setup.py install

And I get the same problem. There are no errors during either installation approach. I've also done the export of PYTHONPATH and, again, same error.

So I guess my question is a simple one: how do you actually get this to work? Or, better, what am I doing wrong (i.e., what steps am I missing?)

**Comment by ppwwyyxx** [comment]
```python
from atari_py import ALEInterface
```

**Comment by jeffnyman** [comment]
@ppwwyyxx Arrgh! Thank you. That was definitely a case of me being an idiot. I was going off of this example from the repo [python_example.py](https://github.com/openai/atari-py/blob/master/doc/examples/python_example.py) and not accounting for the difference in package.

Thank you again!

**Comment by christopherhesse** [comment]
Thanks for answering this @ppwwyyxx!  Looks like that example needs to be updated.
