### ISSUE TITLE
Using ALE 0.6 with atari-py

### ISSUE THREAD

**Issue by gautamb85** [openai/atari-py#23]
Hello,

How can I modify atari-py so that it uses the latest version of ALE (0.6)?

Thanks

**Comment by floringogianu** [comment]
@gautamb85 Any progress on this? I considered it too a couple of weeks ago: openai/gym#820 but waited to see if anyone else working on it already.

**Comment by christopherhesse** [comment]
This would be nice to have, we'd consider any PRs related to this.

**Comment by christopherhesse** [comment]
Someone has opened a PR for this: https://github.com/openai/atari-py/pull/49
