### ISSUE TITLE
Cannot install atari.py on RedHat enterprise server

### ISSUE THREAD

**Issue by dhanush-ai1990** [openai/atari-py#32]
The below are my server details:

Homebrew Ruby: 2.3.7 => /home/dhdharma/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: N/A
Git: 1.8.3.1 => /bin/git
Curl: 7.29.0 => /usr/bin/curl
Java: N/A
Kernel: Linux 3.10.0-693.17.1.el7.x86_64 x86_64 GNU/Linux
OS: Red Hat Enterprise Linux Server release 7.4 (Maipo)
Host glibc: 2.17
/usr/bin/gcc: 4.8.5
glibc: 2.23
gcc: 5.5.0_4
xorg: N/A

When i try to install using
 pip install --user --trusted-host pypi.org --trusted-host files.pythonhosted.org "gym[atari]"

I get the below error:
Building wheels for collected packages: atari-py
  Running setup.py bdist_wheel for atari-py ... error
  Complete output from command /app/ge/aiden/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-x2v7as8m/atari-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-b5rkh8lv --python-tag cp36:
  running bdist_wheel
  running build
  make: Entering directory `/tmp/pip-install-x2v7as8m/atari-py/atari_py/ale_interface'
  mkdir -p build && cd build && cmake .. && make -j4
  -- The C compiler identification is GNU 4.8.5
  -- The CXX compiler identification is GNU 4.8.5
  -- Check for working C compiler: /bin/cc
  -- Check for working C compiler: /bin/cc -- broken
  CMake Error at /root/.local/lib/python3.6/site-packages/cmake/data/share/cmake-3.12/Modules/CMakeTestCCompiler.cmake:52 (message):
    The C compiler
  
      "/bin/cc"
  
    is not able to compile a simple test program.
  
    It fails with the following output:
  
      Change Dir: /tmp/pip-install-x2v7as8m/atari-py/atari_py/ale_interface/build/CMakeFiles/CMakeTmp
  
      Run Build Command:"/bin/gmake" "cmTC_d4bba/fast"
      gmake[1]: Entering directory `/tmp/pip-install-x2v7as8m/atari-py/atari_py/ale_interface/build/CMakeFiles/CMakeTmp'
      /bin/gmake -f CMakeFiles/cmTC_d4bba.dir/build.make CMakeFiles/cmTC_d4bba.dir/build
      gmake[2]: Entering directory `/tmp/pip-install-x2v7as8m/atari-py/atari_py/ale_interface/build/CMakeFiles/CMakeTmp'
      Building C object CMakeFiles/cmTC_d4bba.dir/testCCompiler.c.o
      /bin/cc    -o CMakeFiles/cmTC_d4bba.dir/testCCompiler.c.o   -c /tmp/pip-install-x2v7as8m/atari-py/atari_py/ale_interface/build/CMakeFiles/CMakeTmp/testCCompiler.c
      Linking C executable cmTC_d4bba
      /root/.local/lib/python3.6/site-packages/cmake/data/bin/cmake -E cmake_link_script CMakeFiles/cmTC_d4bba.dir/link.txt --verbose=1
      /bin/cc      -rdynamic CMakeFiles/cmTC_d4bba.dir/testCCompiler.c.o  -o cmTC_d4bba
      /bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../libc.so when searching for -lc
      /bin/ld: skipping incompatible //lib/libc.so when searching for -lc
      /bin/ld: skipping incompatible //usr/lib/libc.so when searching for -lc
      /bin/ld: cannot find -lc
      collect2: error: ld returned 1 exit status
      gmake[2]: *** [cmTC_d4bba] Error 1
      gmake[2]: Leaving directory `/tmp/pip-install-x2v7as8m/atari-py/atari_py/ale_interface/build/CMakeFiles/CMakeTmp'
      gmake[1]: *** [cmTC_d4bba/fast] Error 2
      gmake[1]: Leaving directory `/tmp/pip-install-x2v7as8m/atari-py/atari_py/ale_interface/build/CMakeFiles/CMakeTmp'
  
  
  
  
    CMake will not be able to correctly generate this project.
  Call Stack (most recent call first):
    CMakeLists.txt:2 (project)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-x2v7as8m/atari-py/atari_py/ale_interface/build/CMakeFiles/CMakeOutput.log".
  See also "/tmp/pip-install-x2v7as8m/atari-py/atari_py/ale_interface/build/CMakeFiles/CMakeError.log".
  make: *** [build] Error 1
  make: Leaving directory `/tmp/pip-install-x2v7as8m/atari-py/atari_py/ale_interface'
  Could not build atari-py: Command '['make', 'build', '-C', 'atari_py/ale_interface', '-j', '47']' returned non-zero exit status 2.. (HINT: are you sure cmake is installed? You might also be missing a library. Atari-py requires: zlib [installable as 'apt-get install zlib1g-dev' on Ubuntu].)
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-x2v7as8m/atari-py/setup.py", line 36, in <module>
      tests_require=['nose2']
    File "/app/ge/aiden/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/app/ge/aiden/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/app/ge/aiden/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/app/ge/aiden/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/app/ge/aiden/anaconda3/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 202, in run
      self.run_command('build')
    File "/app/ge/aiden/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/app/ge/aiden/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-x2v7as8m/atari-py/setup.py", line 16, in run
      subprocess.check_call(cmd)
    File "/app/ge/aiden/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['make', 'build', '-C', 'atari_py/ale_interface', '-j', '47']' returned non-zero exit status 2.
  
  ----------------------------------------
  Failed building wheel for atari-py
  Running setup.py clean for atari-py
Failed to build atari-py
Installing collected packages: atari-py
  Running setup.py install for atari-py ... error
    Complete output from command /app/ge/aiden/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-x2v7as8m/atari-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-f95derlu/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    make: Entering directory `/tmp/pip-install-x2v7as8m/atari-py/atari_py/ale_interface'
    mkdir -p build && cd build && cmake .. && make -j4
    -- The C compiler identification is GNU 4.8.5
    -- The CXX compiler identification is GNU 4.8.5
    -- Check for working C compiler: /bin/cc
    -- Check for working C compiler: /bin/cc -- broken
    CMake Error at /root/.local/lib/python3.6/site-packages/cmake/data/share/cmake-3.12/Modules/CMakeTestCCompiler.cmake:52 (message):
      The C compiler
    
        "/bin/cc"
    
      is not able to compile a simple test program.
    
      It fails with the following output:
    
        Change Dir: /tmp/pip-install-x2v7as8m/atari-py/atari_py/ale_interface/build/CMakeFiles/CMakeTmp
    
        Run Build Command:"/bin/gmake" "cmTC_1fbcc/fast"
        gmake[1]: Entering directory `/tmp/pip-install-x2v7as8m/atari-py/atari_py/ale_interface/build/CMakeFiles/CMakeTmp'
        /bin/gmake -f CMakeFiles/cmTC_1fbcc.dir/build.make CMakeFiles/cmTC_1fbcc.dir/build
        gmake[2]: Entering directory `/tmp/pip-install-x2v7as8m/atari-py/atari_py/ale_interface/build/CMakeFiles/CMakeTmp'
        Building C object CMakeFiles/cmTC_1fbcc.dir/testCCompiler.c.o
        /bin/cc    -o CMakeFiles/cmTC_1fbcc.dir/testCCompiler.c.o   -c /tmp/pip-install-x2v7as8m/atari-py/atari_py/ale_interface/build/CMakeFiles/CMakeTmp/testCCompiler.c
        Linking C executable cmTC_1fbcc
        /root/.local/lib/python3.6/site-packages/cmake/data/bin/cmake -E cmake_link_script CMakeFiles/cmTC_1fbcc.dir/link.txt --verbose=1
        /bin/cc      -rdynamic CMakeFiles/cmTC_1fbcc.dir/testCCompiler.c.o  -o cmTC_1fbcc
        /bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../libc.so when searching for -lc
        /bin/ld: skipping incompatible //lib/libc.so when searching for -lc
        /bin/ld: skipping incompatible //usr/lib/libc.so when searching for -lc
        /bin/ld: cannot find -lc
        collect2: error: ld returned 1 exit status
        gmake[2]: *** [cmTC_1fbcc] Error 1
        gmake[2]: Leaving directory `/tmp/pip-install-x2v7as8m/atari-py/atari_py/ale_interface/build/CMakeFiles/CMakeTmp'
        gmake[1]: *** [cmTC_1fbcc/fast] Error 2
        gmake[1]: Leaving directory `/tmp/pip-install-x2v7as8m/atari-py/atari_py/ale_interface/build/CMakeFiles/CMakeTmp'
    
    
    
    
      CMake will not be able to correctly generate this project.
    Call Stack (most recent call first):
      CMakeLists.txt:2 (project)
    
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-install-x2v7as8m/atari-py/atari_py/ale_interface/build/CMakeFiles/CMakeOutput.log".
    See also "/tmp/pip-install-x2v7as8m/atari-py/atari_py/ale_interface/build/CMakeFiles/CMakeError.log".
    make: *** [build] Error 1
    make: Leaving directory `/tmp/pip-install-x2v7as8m/atari-py/atari_py/ale_interface'
    Could not build atari-py: Command '['make', 'build', '-C', 'atari_py/ale_interface', '-j', '47']' returned non-zero exit status 2.. (HINT: are you sure cmake is installed? You might also be missing a library. Atari-py requires: zlib [installable as 'apt-get install zlib1g-dev' on Ubuntu].)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-x2v7as8m/atari-py/setup.py", line 36, in <module>
        tests_require=['nose2']
      File "/app/ge/aiden/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/app/ge/aiden/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/app/ge/aiden/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/app/ge/aiden/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/app/ge/aiden/anaconda3/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/app/ge/aiden/anaconda3/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/app/ge/aiden/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/app/ge/aiden/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-x2v7as8m/atari-py/setup.py", line 16, in run
        subprocess.check_call(cmd)
      File "/app/ge/aiden/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', 'build', '-C', 'atari_py/ale_interface', '-j', '47']' returned non-zero exit status 2.
    
    ----------------------------------------
Command "/app/ge/aiden/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-x2v7as8m/atari-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-f95derlu/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-x2v7as8m/atari-py/

**Comment by christopherhesse** [comment]
This looks like your system is totally broken, are you able to build any software on there?  Also, do the binary linux wheels not work for you?

**Comment by jkterry1** [comment]
Closing due to lack of response
