### ISSUE TITLE
Please stop bumping the version number with no reason

### ISSUE THREAD

**Issue by Kojoley** [openai/atari-py#39]
There was only one code change since `0.1.1` https://github.com/openai/atari-py/compare/f5a1d321bf997ed8a0cda2270f73384b1c792186..master, but the version was bumped six times. CI script updates and even that single code change does not affect library functionality, but you are making headaches for those who have patched `atari_py` and makes `pip install -U` to pull updates for other libraries.

**Comment by christopherhesse** [comment]
Will do, thanks for letting us know!

**Comment by Kojoley** [comment]
And, you again done it...

**Comment by christopherhesse** [comment]
Whoops sorry, those are different test versions of the windows build but they're not on master yet.  Out of curiosity, how does this break your setup?

**Comment by Kojoley** [comment]
I get complains from users of my fork.

P.S. I bumped the major version number in the fork to protect from the future version bumps in the upstream.
