### ISSUE TITLE
saveScreenPNG triggers assertion error for Amidar

### ISSUE THREAD

**Issue by etosch** [openai/atari-py#42]
> repl> import atari_py
> repl> from atari_py.ale_python_interface import ALEInterface
> repl> game_path = atari_py.get_game_path('amidar')
> repl> ale = ALEInterface()
> repl> ale.loadROM(str.encode(game_path))
> repl> ale.act(2)
> repl> ale.saveScreenPNG(str.encode('fooo.png'))
Assertion failed: ((val & 0x01) == 0), function getRGB, file /private/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/pip-req-build-j05pw3nn/build/lib.macosx-10.6-intel-3.6/atari_py/ale_interface/src/common/ColourPalette.cpp, line 51.
Abort trap: 6

This error does not occur for Breakout, nor SpaceInvaders. Using atari-py (0.1.1) with python 3.5.2.

**Comment by jjfiv** [comment]
It looks like atari-py hard-codes a color palette for atari games, and exposes it through ``ale.getScreenRGB2()`` which avoids this logic in ALE -- but ``saveScreenPNG`` goes around the custom palette.

Try:
```python
from PIL import Image
img = Image.fromarray(ale.getScreenRGB2(), 'RGB')
img.save("foo.png", format='png')
```

**Comment by christopherhesse** [comment]
Thanks for answering this @jjfiv!  Maybe we should not expose this function.
