### ISSUE TITLE
Issues in installation on ubuntu 14.04 (x86_64)

### ISSUE THREAD

**Issue by aishwaryyasarkar** [openai/atari-py#43]
I am trying to install atari.py from this repository. I have cmake, make and zlib1g already installed and I have pip version 19.0.2. But when I run the command
`pip install -e .`

I get the following error - 

> aishwarya@aishwarya-Precision-T1600:~/Documents/atari-py$ pip install -e .Obtaining file:///home/aishwarya/Documents/atari-py
Requirement already satisfied: numpy in /home/aishwarya/anaconda3/lib/python3.6/site-packages (from atari-py==0.1.7) (1.14.3)
Requirement already satisfied: six in /home/aishwarya/anaconda3/lib/python3.6/site-packages (from atari-py==0.1.7) (1.11.0)
Installing collected packages: atari-py
  Running setup.py develop for atari-py
    Complete output from command /home/aishwarya/anaconda3/bin/python -c "import setuptools, tokenize;__file__='/home/aishwarya/Documents/atari-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    running develop
    running egg_info
    writing atari_py.egg-info/PKG-INFO
    writing dependency_links to atari_py.egg-info/dependency_links.txt
    writing requirements to atari_py.egg-info/requires.txt
    writing top-level names to atari_py.egg-info/top_level.txt
    reading manifest file 'atari_py.egg-info/SOURCES.txt'
    writing manifest file 'atari_py.egg-info/SOURCES.txt'
    running build_ext
    Unable to execute 'make build -C atari_py/ale_interface -j 7'. HINT: are you sure `make` is installed?
    error: [Errno 2] No such file or directory: 'build/lib.linux-x86_64-3.6': 'build/lib.linux-x86_64-3.6'
    Command "/home/aishwarya/anaconda3/bin/python -c "import setuptools, tokenize;__file__='/home/aishwarya/Documents/atari-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/aishwarya/Documents/atari-py/

I have checked if make, cmake and zlib1g was installed. This is the result telling me that it was already installed. 

> aishwarya@aishwarya-Precision-T1600:~/Documents/atari-py$ sudo apt-get install make
Reading package lists... Done
Building dependency tree       
Reading state information... Done
make is already the newest version.
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra libqpdf13
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 360 not upgraded.
aishwarya@aishwarya-Precision-T1600:~/Documents/atari-py$ sudo apt-get install cmake
Reading package lists... Done
Building dependency tree       
Reading state information... Done
cmake is already the newest version.
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra libqpdf13
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 360 not upgraded.
aishwarya@aishwarya-Precision-T1600:~/Documents/atari-py$ sudo apt-get install zlib1g-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
zlib1g-dev is already the newest version.
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra libqpdf13
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 360 not upgraded.

**Comment by christopherhesse** [comment]
This should be fixed now.
