### ISSUE TITLE
"surround" is missing

### ISSUE THREAD

**Issue by lespeholt** [openai/atari-py#48]
The rom for surround is missing.

**Comment by christopherhesse** [comment]
It looks like support for that game is missing in ALE: https://github.com/mgbellemare/Arcade-Learning-Environment/issues/172

**Comment by christopherhesse** [comment]
Nevertheless, the md5 is included in ALE, the new script to import roms will include surround assuming it's present: https://github.com/openai/atari-py/pull/62
