### ISSUE TITLE
 how to install atari-py in windows?

### ISSUE THREAD

**Issue by momire** [openai/atari-py#5]
i installed gnuwin, cmake for make, cmake command.

 make: Entering directory `C:/Users/ADMINI~1/AppData/Local/Temp/pip-build-i8domwa1/atari-py/atari_py/ale_interface'
  mkdir -p build && cd build && cmake .. && make -j4
  -- Building for: Visual Studio 14 2015
  -- The C compiler identification is unknown
  -- The CXX compiler identification is unknown
  CMake Error at CMakeLists.txt:2 (project):
    No CMAKE_C_COMPILER could be found.

i can't find this problem's solution.

i can't inglish well. sorry.  :3

**Comment by momire** [comment]
these questions are not asked here..
also delete is impossible.. sorry.

**Comment by Chunde** [comment]
I have same situation, not able to install in windows 10.

```
Building wheels for collected packages: atari-py, PyOpenGL
  Running setup.py bdist_wheel for atari-py ... error
  Complete output from command c:\users\chunde\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Chunde\\AppData\\Local\\Temp\\pip-build-b9zparlr\\atari-py\\setup.py';f=getattr(tokenize, 'open', open)(__file__)
;code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Chunde\AppData\Local\Temp\tmp3x8u_yg0pip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  Unable to execute 'make build -C atari_py/ale_interface -j 11'. HINT: are you sure `make` is installed?
  error: [WinError 2] The system cannot find the file specified

  ----------------------------------------
  Failed building wheel for atari-py
  Running setup.py clean for atari-py
  Running setup.py bdist_wheel for PyOpenGL ... done
  Stored in directory: C:\Users\Chunde\AppData\Local\pip\Cache\wheels\1c\17\50\f69d63e0a8169fb890f5a167817a73391be85d30e86fd29504
Successfully built PyOpenGL
Failed to build atari-py
Installing collected packages: atari-py, PyOpenGL
  Running setup.py install for atari-py ... error
    Complete output from command c:\users\chunde\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Chunde\\AppData\\Local\\Temp\\pip-build-b9zparlr\\atari-py\\setup.py';f=getattr(tokenize, 'open', open)(__file_
_);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Chunde\AppData\Local\Temp\pip-c4h2akkk-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    Unable to execute 'make build -C atari_py/ale_interface -j 11'. HINT: are you sure `make` is installed?
    error: [WinError 2] The system cannot find the file specified

    ----------------------------------------
Command "c:\users\chunde\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Chunde\\AppData\\Local\\Temp\\pip-build-b9zparlr\\atari-py\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace
('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Chunde\AppData\Local\Temp\pip-c4h2akkk-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\User
s\Chunde\AppData\Local\Temp\pip-build-b9zparlr\atari-py\
```

**Comment by Chunde** [comment]
Too bad, seems this repo is dead, no one try to help!

**Comment by tlbtlbtlb** [comment]
Atari-py doesn't have support for Windows. It might be possible to port it, but it'll take some programming. Start by following the first hint in the error message:

> `HINT: are you sure `make` is installed?`

and install make.

**Comment by ViktorM** [comment]
I have the same error installing on Windows 10.

**Comment by j8lp** [comment]
Hey everyone.  So I did an automatic merge of rybskej's atari-py windows compatibility repo with the latest version of atari-py, and it seems to work for me on Windows 10.  Just clone and follow rybskej's instructions in the README.  

https://github.com/j8lp/atari-py

**Comment by ViktorM** [comment]
@j8lp trying test run of Atari env I've got an error. Does it sound familiar to you?
```
>>> import gym
>>> env = gym.make('Pong-v0')
[2017-06-11 15:35:21,791] Making new env: Pong-v0
>>> env.reset()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Viktor\Anaconda3\envs\deep-rl\lib\site-packages\gym\core.py", line 107, in reset
    return self._reset()
  File "C:\Users\Viktor\Anaconda3\envs\deep-rl\lib\site-packages\gym\wrappers\time_limit.py", line 49, in _reset
    return self.env.reset()
  File "C:\Users\Viktor\Anaconda3\envs\deep-rl\lib\site-packages\gym\core.py", line 107, in reset
    return self._reset()
  File "C:\Users\Viktor\Anaconda3\envs\deep-rl\lib\site-packages\gym\envs\atari\atari_env.py", line 105, in _reset
    return self._get_obs()
  File "C:\Users\Viktor\Anaconda3\envs\deep-rl\lib\site-packages\gym\envs\atari\atari_env.py", line 99, in _get_obs
    img = self._get_image()
  File "C:\Users\Viktor\Anaconda3\envs\deep-rl\lib\site-packages\gym\envs\atari\atari_env.py", line 86, in _get_image
    return self.ale.getScreenRGB2()
AttributeError: 'ALEInterface' object has no attribute 'getScreenRGB2'
```

**Comment by ViktorM** [comment]
Sounds like this issue: https://github.com/openai/gym/issues/556 Haven't resolved it yet.

**Comment by Dzugaru** [comment]
@ViktorM 
Was getting this error too, for https://github.com/rybskej/atari-py repo, which seems outdated.
I merged openai/atari-py repo into it, as j8lp did, and everything worked fine for me.

**Comment by j8lp** [comment]
@ViktorM sorry I missed your comment previously.  It looks like you still have the older version of atari-py.  Can you try doing a pip uninstall and then following the install instructions again from my repo?

**Comment by ViktorM** [comment]
@j8lp I've fixed errors for quit a long time. The source of the error was older atari version due to the wrong clone link in the description. Now everything works, that was a fix: https://github.com/j8lp/atari-py/commit/20a304c9583bde97b68c85e388ab1cb6b19583d2

**Comment by richielo** [comment]
Hi @j8lp , I have followed the README, but it's still giving errors when use make to make the program. Any idea what's going on? Thanks a lot in advance

> Determining if the C compiler works failed with the following output:
Change Dir: C:/Users/richi/Desktop/DABLab RA/atari-py/atari_py/ale_interface/build/CMakeFiles/CMakeTmp

Run Build Command:"C:/PROGRA~2/Gow/bin/make.exe" "cmTC_048b8/fast"
make.exe[2]: Entering directory `C:/Users/richi/Desktop/DABLab RA/atari-py/atari_py/ale_interface/build/CMakeFiles/CMakeTmp'

C:/PROGRA~2/Gow/bin/make.exe -f CMakeFiles/cmTC_048b8.dir/build.make CMakeFiles/cmTC_048b8.dir/build

make.exe[3]: Entering directory `C:/Users/richi/Desktop/DABLab RA/atari-py/atari_py/ale_interface/build/CMakeFiles/CMakeTmp'

Building C object CMakeFiles/cmTC_048b8.dir/testCCompiler.c.obj

/C/msys64/mingw64/bin/gcc.exe    -o CMakeFiles/cmTC_048b8.dir/testCCompiler.c.obj   -c "/C/Users/richi/Desktop/DABLab RA/atari-py/atari_py/ale_interface/build/CMakeFiles/CMakeTmp/testCCompiler.c"

Linking C executable cmTC_048b8.exe

/C/msys64/mingw64/bin/cmake.exe -E remove -f CMakeFiles/cmTC_048b8.dir/objects.a

process_begin: CreateProcess(NULL, /C/msys64/mingw64/bin/cmake.exe -E remove -f CMakeFiles/cmTC_048b8.dir/objects.a, ...) failed.

make (e=2): The system cannot find the file specified.


make.exe[3]: *** [cmTC_048b8.exe] Error 2

make.exe[3]: Leaving directory `C:/Users/richi/Desktop/DABLab RA/atari-py/atari_py/ale_interface/build/CMakeFiles/CMakeTmp'

make.exe[2]: *** [cmTC_048b8/fast] Error 2

make.exe[2]: Leaving directory `C:/Users/richi/Desktop/DABLab RA/atari-py/atari_py/ale_interface/build/CMakeFiles/CMakeTmp'

**Comment by bhatiaabhinav** [comment]
@j8lp your solution works .. how about submitting a pull request.

**Comment by super999** [comment]
thank you , thank you all. @j8lp  's solution works for me. My environment is , OS: Window 10 (1709 16299.125) , Python: 3.5.3 v1900 64bit . tensorflow: tf.__version__ '1.4.0' .

**Comment by YitzhakSp** [comment]
the solution of @j8lp  doesn't work for me. Python is struggling to load the libale_c.dll. my OS:
win 10, (64bit)
python 3.6
msys (64 bit version)
Here's the error
```
Traceback (most recent call last):
  File "C:/Users/Yitzhak/Projects/rl_with_gym/test3.py", line 6, in <module>
    env = gym.make("Pong-v0")
  File "C:\Users\Yitzhak\Anaconda3\envs\pyth_35\lib\site-packages\gym\envs\registration.py", line 167, in make
    return registry.make(id)
  File "C:\Users\Yitzhak\Anaconda3\envs\pyth_35\lib\site-packages\gym\envs\registration.py", line 119, in make
    env = spec.make()
  File "C:\Users\Yitzhak\Anaconda3\envs\pyth_35\lib\site-packages\gym\envs\registration.py", line 85, in make
    cls = load(self._entry_point)
  File "C:\Users\Yitzhak\Anaconda3\envs\pyth_35\lib\site-packages\gym\envs\registration.py", line 14, in load
    result = entry_point.load(False)
  File "C:\Users\Yitzhak\Anaconda3\envs\pyth_35\lib\site-packages\pkg_resources\__init__.py", line 2341, in load
    return self.resolve()
  File "C:\Users\Yitzhak\Anaconda3\envs\pyth_35\lib\site-packages\pkg_resources\__init__.py", line 2347, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Users\Yitzhak\Anaconda3\envs\pyth_35\lib\site-packages\gym\envs\atari\__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "C:\Users\Yitzhak\Anaconda3\envs\pyth_35\lib\site-packages\gym\envs\atari\atari_env.py", line 9, in <module>
    import atari_py
  File "C:\Users\Yitzhak\Anaconda3\envs\pyth_35\lib\site-packages\atari_py-0.1.1-py3.5.egg\atari_py\__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "C:\Users\Yitzhak\Anaconda3\envs\pyth_35\lib\site-packages\atari_py-0.1.1-py3.5.egg\atari_py\ale_python_interface.py", line 14, in <module>
    'ale_interface/build/libale_c.dll'))
  File "C:\Users\Yitzhak\Anaconda3\envs\pyth_35\lib\ctypes\__init__.py", line 429, in LoadLibrary
    tmp=self._dlltype(name)
  File "C:\Users\Yitzhak\Anaconda3\envs\pyth_35\lib\ctypes\__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
```

**Comment by ikamensh** [comment]
I had this problem too.
A painless way to install atari-py on windows:
https://stackoverflow.com/questions/42605769/openai-gym-atari-on-windows/46739299

**Comment by dhanush987** [comment]
Can i install atari.py on a RedHat server .

Kernel: Linux 3.10.0-693.17.1.el7.x86_64 x86_64 GNU/Linux
OS: Red Hat Enterprise Linux Server release 7.4 (Maipo)

**Comment by Watesoyan** [comment]
@ikamensh Thank you so much. It really solve my problem in win7 64bit.

**Comment by christopherhesse** [comment]
This should be fixed by https://github.com/openai/atari-py/pull/50
