### ISSUE TITLE
Speed optimization PR in ALE

### ISSUE THREAD

**Issue by mgbellemare** [openai/atari-py#60]
I believe you keep a close eye on the ALE repo, but just as additional FYI, there is an optimization PR from @qstanczyk that inlines some code for additional performance, and will be merged soon: https://github.com/mgbellemare/Arcade-Learning-Environment/pull/265 . Thanks!

**Comment by christopherhesse** [comment]
Thanks for the heads up!

**Comment by oars** [comment]
Any chance of updating ALE here?

**Comment by jkterry1** [comment]
Hey, I'm closing this with the release of ALE-Py
