### ISSUE TITLE
Building requires zlib1g-dev, not just zlib1g

### ISSUE THREAD

**Issue by justinkterry** [openai/atari-py#66]
This isn't stated in the readme, and without the dev version installed you get the following incredibly opaque build error:

>     /home/justinkterry/Documents/atari-py/atari_py/ale_interface/src/common/ScreenExporter.cpp:18:10: fatal error: zlib.h: No such file or directory
>      #include <zlib.h>
>               ^~~~~~~~
>     compilation terminated.

You should at least update the readme file to reflect this, and ideally include a check with a useful error message during building

**Comment by christopherhesse** [comment]
Added that to the readme.  This is just normal dev stuff though, the precompiled binaries are there to prevent users from having to deal with this stuff in general.  Thanks for filing the issue!
