### ISSUE TITLE
Update atari-py from upstream ALE

### ISSUE THREAD

**Issue by christopherhesse** [openai/atari-py#67]
We should update the version of ALE used in atari-py to get at least the following changes:

* https://github.com/mgbellemare/Arcade-Learning-Environment/pull/265
* https://github.com/mgbellemare/Arcade-Learning-Environment/pull/264

This might be a good chance to re-structure the repo as a fork of ALE instead of manually updating.

**Comment by jkterry1** [comment]
Closed as Atari-Py has been deprecated in favor of ALE-Py
