### ISSUE TITLE
Compatilbility with Python 3.8?

### ISSUE THREAD

**Issue by yganjali** [openai/atari-py#72]
Is atari-py compatible with Python 3.8? I'm trying to install it on a MacOS (Catalina) with Python 3.8 installed, but keep getting errors.

Any help on this would be appreciated.

Thank you.

**Comment by craftsliu** [comment]
i have encountered the same problems,do you solve it now ?

**Comment by craftsliu** [comment]
> i have encountered the same problems,do you solve it now ?

I just solve it by using python=3.7
