### ISSUE TITLE
Cannot find the game surround that is part of the Atari57 benchmark

### ISSUE THREAD

**Issue by danijar** [openai/atari-py#73]
@christopherhesse Would it be possible to add this to allow comparison to DeepMind papers? Or perhaps, if it's there and I missed, how can I use it? Gym doesn't find an env `Surround-v0'.

**Comment by christopherhesse** [comment]
This is an ALE issue: https://github.com/mgbellemare/Arcade-Learning-Environment/issues/172

**Comment by danijar** [comment]
The issue you linked has been resolved in this PR: https://github.com/mgbellemare/Arcade-Learning-Environment/pull/327

**Comment by JesseFarebro** [comment]
We're currently working on migrating upstream ALE to interface directly with Gym. There's still some work to go before this is complete. You could build the ALE Python wrapper directly and use that for the time being (if you just need Surround results). I'll prewarn you that there is an issue with SwapPort and various games https://github.com/mgbellemare/Arcade-Learning-Environment/pull/347 so if you are building from master be aware of this, games like Wizar of Wor don't currently work on master.
