### ISSUE TITLE
Publish wheels for 3.8

### ISSUE THREAD

**Issue by tgolsson** [openai/atari-py#78]
Hello!

This repo seems to be quite dead; but I'd love if there was prebuilt wheel for Python 3.8. It seems to build fine if you pip install; but it takes quite a long while. I tried updating the cloud build but I couldn't quite get all the scripts and states to work. I'll happily do the work as far as I can if it'll get accepted, but I can't likely make the final push for it.

**Comment by joaogui1** [comment]
@adversariel seems to have released it, do they work? Should the readme be updated?
