### ISSUE TITLE
Exception: ROM is missing for ms_pacman, see https://github.com/openai/atari-py#roms for instructions

### ISSUE THREAD

**Issue by astrotech-test** [openai/atari-py#81]
I am totally new to OpenAi gym, I have just installed gym and then try to make environment for 
`env = gym.make('MsPacman-v0')` so I am getting the following error:

    ---------------------------------------------------------------------------
    Exception                                 Traceback (most recent call last)
    <ipython-input-21-e04adf623175> in <module>
    ----> 1 env = gym.make('MsPacman-v0')
    
    ~\Anaconda3\envs\env_project\lib\site-packages\gym\envs\registration.py in make(id, **kwargs)

    ~\Anaconda3\envs\env_project\lib\site-packages\gym\envs\registration.py in make(self, path, **kwargs)

    ~\Anaconda3\envs\env_project\lib\site-packages\gym\envs\registration.py in make(self, **kwargs)

    ~\Anaconda3\envs\env_project\lib\site-packages\gym\envs\atari\atari_env.py in __init__(self, game, 
    mode, difficulty, obs_type, frameskip, repeat_action_probability, full_action_space)

    ~\Anaconda3\envs\env_project\lib\site-packages\atari_py\games.py in get_game_path(game_name)
     18     path = os.path.join(_games_dir, game_name) + ".bin"
     19     if not os.path.exists(path):
    ---> 20         raise Exception('ROM is missing for %s, see https://github.com/openai/atari-py#roms 
    for instructions' % (game_name,))
     21     return path
     22 

    Exception: ROM is missing for ms_pacman, see https://github.com/openai/atari-py#roms for instructions

After this I also tried to find the solution on the web and download the [ROMs][1] and extracted in a folder then hit the command `python -m atari_py.import_roms <path where ROMs downloaded>`, after running this command I am also getting following error 

    (env_project) C:\Users\ME>python -m atari_py.import_roms C:\Users\ME\Downloads\roms_folder\
    
    copying adventure.bin from HC ROMS/BY ALPHABET (PAL)/A-G/Adventure (PAL).bin to 
    C:\Users\ME\Anaconda3\envs\env_project\lib\site-packages\atari_py\atari_roms\adventure.bin
    Traceback (most recent call last):
    File "C:\Users\ME\Anaconda3\envs\env_project\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
    File "C:\Users\ME\Anaconda3\envs\env_project\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
    File "C:\Users\ME\Anaconda3\envs\env_project\lib\site-packages\atari_py\import_roms.py", line 93, 
    in <module>
    main()
    File "C:\Users\ME\Anaconda3\envs\env_project\lib\site-packages\atari_py\import_roms.py", line 89, 
    in main
    import_roms(args.dirpath)
    File "C:\Users\ME\Anaconda3\envs\env_project\lib\site-packages\atari_py\import_roms.py", line 78, 
    in import_roms
    _check_zipfile(f, save_if_matches)
    File "C:\Users\ME\Anaconda3\envs\env_project\lib\site-packages\atari_py\import_roms.py", line 23, 
    in _check_zipfile
    process_f(innerf)
    File "C:\Users\ME\Anaconda3\envs\env_project\lib\site-packages\atari_py\import_roms.py", line 67, 
    in save_if_matches
    f.seek(0)
    io.UnsupportedOperation: seek

I don't know what I am doing wrong. Thank in advance.

  [1]: https://github.com/openai/atari-py

**Comment by Kin-Zhang** [comment]
I also reach this error when I do
```bash
python -m atari_py.import_roms <path where ROMs downloaded>
```
And I searched for a while, find another issue: https://github.com/openai/atari-py/issues/84 which change env to python 3.7

**Comment by tianyma** [comment]
import urllib.request
urllib.request.urlretrieve('http://www.atarimania.com/roms/Roms.rar','Roms.rar')
!pip install unrar
!unrar x Roms.rar
!mkdir rars
!mv HC\ ROMS.zip   rars
!mv ROMS.zip  rars
!python -m atari_py.import_roms rars
-----------------------------------------------
this should work.

**Comment by tianyma** [comment]
import urllib.request
urllib.request.urlretrieve('http://www.atarimania.com/roms/Roms.rar','Roms.rar')
!pip install unrar
!unrar x Roms.rar
!mkdir rars
!mv HC\ ROMS.zip   rars
!mv ROMS.zip  rars
!python -m atari_py.import_roms rars

**Comment by silentriverg** [comment]
I also met the io.UnsupportedOperation: seek problem and solve by this way:

Download the Roms.rar, unrar and unzip the package twice in Windows:
step1: unrar Roms.rar to HC ROMS.zip and ROMS.zip
steps: unzip HC ROMS.zip and ROMS.zip to 2 folders, HC ROMS and ROMS

send these 2 folders to linux server, for example, using sftp

run python -m atari_py.import_roms <path>

don't unrar or unzip directly in linux server, don't pull from rar window directly to sftp window, in these attempts I met io.UnsupportedOperation: seek error

**Comment by astrotech-test** [comment]
Thanks @tianyma this worked for me.
