### ISSUE TITLE
Rom is missing, Fix that please X-X 

### ISSUE THREAD

**Issue by Julian566** [openai/atari-py#82]
Exception                                 Traceback (most recent call last)
<ipython-input-11-7af2597d0a5a> in <module>()
      1 def create_pong_env():
      2   return gym.make("Pong-v0", frameskip=5)
----> 3 env = create_pong_env()
      4 env.seed(1); # for reproducibility

5 frames
/usr/local/lib/python3.7/dist-packages/atari_py/games.py in get_game_path(game_name)
     18     path = os.path.join(_games_dir, game_name) + ".bin"
     19     if not os.path.exists(path):
---> 20         raise Exception('ROM is missing for %s, see https://github.com/openai/atari-py#roms for instructions' % (game_name,))
     21     return path
     22 

Exception: ROM is missing for pong, see https://github.com/openai/atari-py#roms for instructions

**Comment by Ryan-Rudes** [comment]
Very strange; I experienced the same thing for the first time today.

**Comment by tfboyd** [comment]
@Julian566    atari-py no longer has the pong.rom included. I am not sure why but you can find by downloading the roms at the link it is suggesting you visit.  The pong is under ./BY ALPHABET/S-Z/Video Olympics - Pong Sports.bin which is in the HC ROMS. I had a hard time using unrar on windows but it worked fine on linux.  

This should get you most of the way.:

```bash
wget http://www.atarimania.com/roms/Roms.rar && unrar x Roms.rar && unzip ROMS.zip && unzip HC\ ROMS.zip 
```

**Comment by Art-Vs17** [comment]
import urllib.request
urllib.request.urlretrieve('http://www.atarimania.com/roms/Roms.rar','Roms.rar')
!pip install unrar
!unrar x Roms.rar
!mkdir rars
!mv HC\ ROMS.zip   rars
!mv ROMS.zip  rars
!python -m atari_py.import_roms rars
