### ISSUE TITLE
Problem in Google colab with "Breakout" game in OpenAI Gym (ROM missing)

### ISSUE THREAD

**Issue by amitjo** [openai/atari-py#83]
Browser: Chrome

Creating env for "Breakout" game from OpenAI Gym is giving problem in Googlw colab. Following is the error message that pops up.

Note: This problem seems to be a recent issue. It was a working code till 2 days back and suddenly started giving problems.

############################################################################################

Exception Traceback (most recent call last)
in ()
1 if name == 'main':
2
----> 3 env = gym.make('Breakout-v0')
4 load_checkpoint = False
5 agent = Agent(gamma=0.99, epsilon=1.0, alpha=0.000025, input_dims=(180,160,4),

4 frames
/usr/local/lib/python3.7/dist-packages/atari_py/games.py in get_game_path(game_name)
18 path = os.path.join(_games_dir, game_name) + ".bin"
19 if not os.path.exists(path):
---> 20 raise Exception('ROM is missing for %s, see https://github.com/openai/atari-py#roms for instructions' % (game_name,))
21 return path
22

Exception: ROM is missing for breakout, see https://github.com/openai/atari-py#roms for instructions

**Comment by berni-lehner** [comment]
It seems this is a general issue with Colab+gym, I fail to create the pong environment, with the same code that worked flawlessly on Saturday.

**Comment by dusty-keyboard** [comment]
Found a fix. Go to http://www.atarimania.com/rom_collection_archive_atari_2600_roms.html and download the .rar file with the roms.  Extract that .rar file on your local machine.  There are 2 zip files in the extracted folder. Then upload those 2 zip files to you colab project.. inside your colab notebook run the following
`from google.colab import files`
`uploaded = files.upload()`

This will give you a button to browse your local machine. Upload those 2 zip files.

Then in you colab notebook run the following
`!python -m atari_py.import_roms .`

Don't forget the . at the end.  Then you can run atari gym.

**Comment by 0x15F9** [comment]
I was also experiencing the same problem and, based on the previous answers I wrote this short script **to be used in colab**. I hope someone finds it useful.


```bash
! wget http://www.atarimania.com/roms/Roms.rar
! mkdir /content/ROM/
! unrar e /content/Roms.rar /content/ROM/
! python -m atari_py.import_roms /content/ROM/
```

**Comment by alghenab** [comment]
Just copy and Run.
```python
!wget http://www.atarimania.com/roms/Roms.rar
!unrar x /content/Roms.rar /content
!python -m atari_py.import_roms .
```

**Comment by alirezakazemipour** [comment]
@0x15F9 
You have no idea how many times I have come back to and used your solution! :heart: 
Quite a lifesaver! :smile: 
Thanks a lot.
