### ISSUE TITLE
Unable to import ROMS

### ISSUE THREAD

**Issue by Xiaoyang-Lu** [openai/atari-py#92]
Hello,

I followed the instructions to import ROMS, however, I received this message:

> python -m atari_py.import_roms ./Roms/ROMS
> Traceback (most recent call last):
>   File "/Users/rosen/opt/anaconda3/envs/rl_p2/lib/python3.5/runpy.py", line 183, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "/Users/rosen/opt/anaconda3/envs/rl_p2/lib/python3.5/runpy.py", line 153, in _get_module_details
>     code = loader.get_code(mod_name)
>   File "<frozen importlib._bootstrap_external>", line 799, in get_code
>   File "<frozen importlib._bootstrap_external>", line 759, in source_to_code
>   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
>   File "/Users/rosen/opt/anaconda3/envs/rl_p2/lib/python3.5/site-packages/atari_py/import_roms.py", line 57
>     name = f"patched version of {f.name}"
>                                         ^
> SyntaxError: invalid syntax

I don't know why there has a SyntaxError. Do you know what should I do to fix this? 

Thanks.

**Comment by JesseFarebro** [comment]
Hi,

The atari-py package is now deprecated. You should be using the `ale-py` package which provides its own ROM import functionality. You can read more here: https://github.com/mgbellemare/Arcade-Learning-Environment.

Even after upgrading you'll see this syntax error as it seems you're using Python 3.5 which reached end of life as of September, 2020. You should upgrade to at least Python 3.7+. (the specific error is that Python 3.5 doesn't support f-strings introduced in 3.6).
